version: '3.8'

services:
  app:
    build: .
    container_name: tree-shop-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - tree-network

  mongo:
    image: mongo:latest
    container_name: tree-shop-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tree-network

volumes:
  mongo-data:

networks:
  tree-network:
    driver: bridge